name: build-test-and-deploy
on: 
    push:
        branches:
            - main
jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: dotnet build --configuration Release src/MsSqlHelpers/MsSqlHelpers.csproj

    - name: Run tests
      run: dotnet test src/MsSqlHelpers.Tests/MsSqlHelpers.Tests.csproj

    - name: Publish to NuGet
      uses: brandedoutcast/publish-nuget@v2
      with:
          PROJECT_FILE_PATH: src/MsSqlHelpers/MsSqlHelpers.csproj
          NUGET_KEY: ${{secrets.NUGET_TOKEN}}