name: Build, test and deploy package

on: 
    push:
        branches:
            - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Build
      run: dotnet build --configuration Release src/MsSqlHelpers/MsSqlHelpers.csproj

    - name: Test
      run: dotnet test src/MsSqlHelpers.Tests/MsSqlHelpers.Tests.csproj

    - name: Create Package
      run: dotnet pack --configuration Release src/MsSqlHelpers/MsSqlHelpers.csproj

    - name: Publish
      uses: brandedoutcast/publish-nuget@v2
      with:
          PROJECT_FILE_PATH: src/MsSqlHelpers/MsSqlHelpers.csproj
          NUGET_KEY: ${{secrets.NUGET_TOKEN}}